<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
    <context>
        <name>astroseasons.cpp:145</name>
        <message>
            <source>June Solstice</source>
            <translation>Solstici de juny</translation>
        </message>
    </context>
    <context>
        <name>astroseasons.cpp:147</name>
        <message>
            <source>December Solstice</source>
            <translation>Solstici de desembre</translation>
        </message>
    </context>
    <context>
        <name>astroseasons.cpp:149</name>
        <message>
            <source>March Equinox</source>
            <translation>Equinocci de març</translation>
        </message>
    </context>
    <context>
        <name>astroseasons.cpp:151</name>
        <message>
            <source>September Equinox</source>
            <translation>Equinocci de setembre</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:893</name>
        <message>
            <source>Quebec</source>
            <translation>Quebec</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:895</name>
        <message>
            <source>Bavaria</source>
            <translation>Baviera</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:897</name>
        <message>
            <source>Catalonia</source>
            <translation>Catalunya</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:899</name>
        <message>
            <source>England and Wales</source>
            <translation>Anglaterra i Gal·les</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:901</name>
        <message>
            <source>England</source>
            <translation>Anglaterra</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:903</name>
        <message>
            <source>Wales</source>
            <translation>Gal·les</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:905</name>
        <message>
            <source>Scotland</source>
            <translation>Escòcia</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:907</name>
        <message>
            <source>Northern Ireland</source>
            <translation>Irlanda del Nord</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:909</name>
        <message>
            <source>South Tyrol</source>
            <translation>Tirol del sud</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:911</name>
        <message>
            <source>New South Wales</source>
            <translation>Nova Gal·les del sud</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:913</name>
        <message>
            <source>Queensland</source>
            <translation>Queensland</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:915</name>
        <message>
            <source>Victoria</source>
            <translation>Victòria</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:917</name>
        <message>
            <source>South Australia</source>
            <translation>Austràlia Meridional</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:919</name>
        <message>
            <source>Northern Territory</source>
            <translation>Territori del Nord</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:922</name>
        <message>
            <source>Australian Capital Territory</source>
            <translation>Territori de la Capital Australiana</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:925</name>
        <message>
            <source>Western Australia</source>
            <translation>Austràlia Occidental</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:928</name>
        <message>
            <source>Tasmania</source>
            <translation>Tasmània</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:931</name>
        <message>
            <source>Republic of Srpska</source>
            <translation>República Sèrbia</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:950</name>
        <message>
            <source>Public</source>
            <translation>Públic</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:952</name>
        <message>
            <source>Civil</source>
            <translation>Civil</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:954</name>
        <message>
            <source>Religious</source>
            <translation>Religiós</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:956</name>
        <message>
            <source>Government</source>
            <translation>Govern</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:958</name>
        <message>
            <source>Financial</source>
            <translation>Financer</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:960</name>
        <message>
            <source>Cultural</source>
            <translation>Cultural</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:962</name>
        <message>
            <source>Commemorative</source>
            <translation>Commemoratiu</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:964</name>
        <message>
            <source>Historical</source>
            <translation>Històric</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:966</name>
        <message>
            <source>School</source>
            <translation>Escola</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:968</name>
        <message>
            <source>Seasonal</source>
            <translation>Temporada</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:970</name>
        <message>
            <source>Name Days</source>
            <translation>Onomàstica</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:972</name>
        <message>
            <source>Personal</source>
            <translation>Personal</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:974</name>
        <message>
            <source>Christian</source>
            <translation>Cristià</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:976</name>
        <message>
            <source>Anglican</source>
            <translation>Anglicà</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:978</name>
        <message>
            <source>Catholic</source>
            <translation>Catòlic</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:980</name>
        <message>
            <source>Protestant</source>
            <translation>Protestant</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:982</name>
        <message>
            <source>Orthodox</source>
            <translation>Ortodox</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:984</name>
        <message>
            <source>Jewish</source>
            <translation>Jueu</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:986</name>
        <message>
            <source>Jewish Orthodox</source>
            <translation>Judaisme ortodox</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:988</name>
        <message>
            <source>Jewish Conservative</source>
            <translation>Judaisme conservador</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:990</name>
        <message>
            <source>Jewish Reform</source>
            <translation>Judaisme reformista</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:992</name>
        <message>
            <source>Islamic</source>
            <translation>Islàmic</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:994</name>
        <message>
            <source>Islamic Sunni</source>
            <translation>Islam sunní</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:996</name>
        <message>
            <source>Islamic Shia</source>
            <translation>Islam xií</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:998</name>
        <message>
            <source>Islamic Sufi</source>
            <translation>Islam sufí</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:1005</name>
        <message>
            <source>%1 - %2</source>
            <translation>%1 - %2</translation>
        </message>
    </context>
    <context>
        <name>holidayregion.cpp:1015</name>
        <message>
            <source>Unknown</source>
            <translation>Desconegut</translation>
        </message>
    </context>
    <context>
        <name>lunarphase.cpp:46</name>
        <message>
            <source>New Moon</source>
            <translation>Lluna nova</translation>
        </message>
    </context>
    <context>
        <name>lunarphase.cpp:48</name>
        <message>
            <source>Full Moon</source>
            <translation>Lluna plena</translation>
        </message>
    </context>
    <context>
        <name>lunarphase.cpp:50</name>
        <message>
            <source>First Quarter Moon</source>
            <translation>Lluna en quart creixent</translation>
        </message>
    </context>
    <context>
        <name>lunarphase.cpp:52</name>
        <message>
            <source>Last Quarter Moon</source>
            <translation>Lluna en quart minvant</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:79</name>
        <message>
            <source>Aries</source>
            <translation>Àries</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:81</name>
        <message>
            <source>Taurus</source>
            <translation>Taure</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:83</name>
        <message>
            <source>Gemini</source>
            <translation>Gèminis</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:85</name>
        <message>
            <source>Cancer</source>
            <translation>Càncer</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:87</name>
        <message>
            <source>Leo</source>
            <translation>Lleó</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:89</name>
        <message>
            <source>Virgo</source>
            <translation>Verge</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:91</name>
        <message>
            <source>Libra</source>
            <translation>Balança</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:93</name>
        <message>
            <source>Scorpio</source>
            <translation>Escorpió</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:95</name>
        <message>
            <source>Sagittarius</source>
            <translation>Sagitari</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:97</name>
        <message>
            <source>Capricorn</source>
            <translation>Capricorn</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:99</name>
        <message>
            <source>Aquarius</source>
            <translation>Aquari</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:101</name>
        <message>
            <source>Pisces</source>
            <translation>Peixos</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:270</name>
        <message>
            <source>ram</source>
            <translation>moltó</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:272</name>
        <message>
            <source>bull</source>
            <translation>bou</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:274</name>
        <message>
            <source>twins</source>
            <translation>bessons</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:276</name>
        <message>
            <source>crab</source>
            <translation>cranc</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:278</name>
        <message>
            <source>lion</source>
            <translation>lleó</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:280</name>
        <message>
            <source>virgin</source>
            <translation>verge</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:282</name>
        <message>
            <source>scales</source>
            <translation>balança</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:284</name>
        <message>
            <source>scorpion</source>
            <translation>escorpí</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:286</name>
        <message>
            <source>archer</source>
            <translation>arquer</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:288</name>
        <message>
            <source>goat</source>
            <translation>boc</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:290</name>
        <message>
            <source>water carrier</source>
            <translation>portador d'aigua</translation>
        </message>
    </context>
    <context>
        <name>zodiac.cpp:292</name>
        <message>
            <source>fish</source>
            <translation>peix</translation>
        </message>
    </context>
</TS>