#!/bin/bash
PWD=$(pwd)

HEADPREINST='if [ "$1" = "install" || "$1" = "upgrade" ]; then'
FOOTPREINST='fi'


HEADPOSTRM='if [ "$1" = "purge" || "$1" = "remove" || "$1" = "upgrade" ]; then'
FOOTPOSTRM='fi'

echo $HEADPREINST >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper
echo $HEADPOSTRM >> ${PWD}/debian/lliurex-langpack-kde.postrm.debhelper

for POFILE in $(find . -type f -name *.po -not -path debian); do
	echo $POFILE
done




echo $FOOTPREINST >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper
echo $FOOTPOSTRM >> ${PWD}/debian/lliurex-langpack-kde.postrm.debhelper
