#!/bin/bash
PWD=$(pwd)

HEADPREINST='if [ "$1" = "install" || "$1" = "upgrade" ]; then'
FOOTPREINST='fi'


HEADPOSTRM='if [ "$1" = "purge" || "$1" = "remove" || "$1" = "upgrade" ]; then'
FOOTPOSTRM='fi'

echo $HEADPREINST >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper
echo $HEADPOSTRM >> ${PWD}/debian/lliurex-langpack-kde.postrm.debhelper


MOPATH="/usr/share/locale/ca@valencia/LC_MESSAGES/"
INSTALLMOPATH="debian/lliurex-langpack-kde$MOPATH"
mkdir -p $MOPATH

for POFILE in $(find . -type f -name *.po -not -path debian); do
	APPNAME=$(basename $POFILE .po)
	msgfmt $POFILE -o ${INSTALLMOPATH}/$APPNAME.mo
	echo "dpkg-divert --package lliurex-langpack-kde --add --rename ${MOPATH}/$APPNAME.mo" >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper
	echo "dpkg-divert --package lliurex-langpack-kde --remove --rename ${MOPATH}/$APPNAME.mo" >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper

done

echo $FOOTPREINST >> ${PWD}/debian/lliurex-langpack-kde.preinst.debhelper
echo $FOOTPOSTRM >> ${PWD}/debian/lliurex-langpack-kde.postrm.debhelper
