#!/bin/sh
# postrm script for lliurex-langpack-kde
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    failed-upgrade)
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/dolphin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/dolphin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_joystick.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.plasmoidviewer.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.kimpanel.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.panel.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_memory.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdeplasma-addons._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_solid_actions.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/breeze_kwin_deco.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/phonon_kde_plugin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.windowlist.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_search.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/krunner.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/bluedevil.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmview1394.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcminit.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_icons.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin_clients.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kscreenlocker._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kde-gtk-config.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.milou.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.clipboard.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_pulseaudio.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_displayconfiguration.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_cursortheme.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.binaryclock.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwrited._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.analogclock.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin_scripting.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kgamma5._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_splashscreen.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kio5_applications.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkwinrules.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_runner_kwin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.taskmanager.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kscreenlocker.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.discover.packagekit.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmshell5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kinfocenter._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_pci.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/bluedevil_xml_mimetypes.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.minimizeall.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_bolt.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kded_bolt.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/klipper.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/milou.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_componentchooser.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin_scripts.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/breeze._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.kinfocenter.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kactivitymanagerd._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_shell_org.kde.plasma.desktop.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.devicenotifier.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin_effects.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kholidays_calendar_plugin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdeplasma-addons._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmmouse.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/oxygen_style_config.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/attica_kde_plugin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksysguardlsofwidgets.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_baloofile.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmaccess.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmqtquicksettings.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kfontinst.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksmserver.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_desktoppaths.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kactivitymanagerd._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libksysguard._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_device_automounter.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.kscreen.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasmaactivitymanager.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_launchfeedback.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.diskquota.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkeyboard.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_workspace.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_fileindexermonitor.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_colors.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kstart5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_lookandfeel.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_nightcolor.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kio_desktop.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/oxygen_kdecoration.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmusb.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kinfocenter.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kde-cli-tools._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_plymouth.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_kwintabbox.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.discover.flatpak.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/cuttlefish_editorplugin.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/khotkeys.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_energyinfo.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/cuttlefish.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_activities5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kaccess.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.showdesktop.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.appmenu.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_touchpad.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcminfo.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_toolbox_org.kde.paneltoolbox.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwrited._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kioclient5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kmimetypefinder5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdecoration.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/milou._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmstyle.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.comic.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kscreenlocker_greet.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/liboxygenstyleconfig.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmnic.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkwincompositing.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_fonts.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_phonon.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.battery.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kscreen._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.trash.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkwinscreenedges.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.pager.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm-about-distro.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/drkonqi._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkeys.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.discover.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kmenuedit.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.cuttlefish.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmformats.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma_applet_dict.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_touchpad.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_kded.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwallet-pam._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_autostart.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksshaskpass.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_translations.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.plasmaengineexplorer.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmsmserver.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libkworkspace.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkgamma.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/breeze_style_config.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kscreen.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ktraderclient5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/krdb.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_runner_plasma-desktop.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_emoticons.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksgrd.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdesu5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/freespacenotifier.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libnotificationmanager.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksysguard._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/oxygen._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.discovernotifier.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.fifteenpuzzle.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/breeze._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_desktoptheme.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_toolbox_org.kde.desktoptoolbox.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.showActivityManager.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkwincommon.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwin._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_mobile_wifi.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kactivities5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm-kwin-scripts.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.discover.snap.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_kwin_effects.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/knetattach5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_notifications.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.plasmashell.metainfo.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_kwin_virtualdesktops.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.desktopcontainment.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.kicker.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kde-gtk-config._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/bluedevil._json_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmdevinfo.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkwm.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/discover._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.plasma.themeexplorer.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/oxygen._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/drkonqi5.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/bluedevil._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libpowerdevilcommonconfig.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmopengl.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.calendar.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_sddm.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.bluetooth.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.ksysguard.appdata.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcmkclock.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.calculator.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kbroadcastnotification.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm5_filetypes.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.kickoff.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_standard_actions.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kmenuedit._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcm_mobile_broadband.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/khotkeys._desktop_.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ksysguard.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/oxygen_style_demo.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/plasma_applet_org.kde.plasma.colorpicker.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/org.kde.plasma.lookandfeelexplorer.mo
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kjsembed5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kjobwidgets5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kservice5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcoreaddons5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwalletd5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libkxmlrpcclient5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcompletion5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwallet-query.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kglobalaccel5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libkholidays5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kauth5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kitemviews5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwidgetsaddons5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kconfig5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kio5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ktexteditor5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/ktextwidgets5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/sonnet5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kio5_timeline.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kparts5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kunitconversion5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/knotifyconfig5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kwindowsystem5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libkirigami2plugin_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kross5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kxmlgui5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kpeople5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libkpackage5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdnssd5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/knotifications5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kpty5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/solid5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kcodecs5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kdbusaddons5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/knewstuff5.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/kbookmarks5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/syntaxhighlighting5_qt.qm
	dpkg-divert --package lliurex-langpack-kde --quiet --remove /usr/share/locale/ca@valencia/LC_MESSAGES/libplasma5.qm
	    ;;
    purge|remove|upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
